name: algolia
version: 1.0.0-dev.0
authors:
  - Nayan Hathiwala (Knoxpo) <nhathiwala@knoxpo.com>
  - Musa Rikhotso (Disparta) <musadisparta@gmail.com>
description: >
  Algolia is a pure dart SDK, wrapped around Algolia REST API for easy implementation for your Flutter or Dart projects. This version is Null-Safe
homepage: https://github.com/knoxpo/dart_algolia

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0
  uuid: ^3.0.1

dev_dependencies:
  test: ^1.16.5
